config/routes.rb
RailsProvingGround::Application.routes.draw do

  root          to: "roots#index"
  get :bunseki, to: "roots#bunseki", as: "bunseki"
  get :study,   to: "roots#study",   as: "study"
  get :work,    to: "roots#work",    as: "work"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #layout 'yeti'
end

app/controllers/roots_controller.rb
# encoding: utf-8
class RootsController < ApplicationController
  #before_filter :authenticate, only: [:study, :work]
   
  def index
  end

  # 成分分析プログラム
  def bunseki
    @name = params[:name]
    if @name.present?
      @name = "文字列長すぎマン" if @name.length > 30
      per_list = []
      @seibun_list = []
      file = open(Rails.root.join("public/seibun_list.txt"))
      seibun_key = file.readlines
      nokori = 100
      number = Digest::MD5.new.update(@name).to_s.to_i(16)
      while true
        per = (nokori < 10) ? nokori : number % (nokori + 1)
        per = 1 if per == 0
        per_list.push per
        @seibun_list.push seibun_key[number%(seibun_key.length)].chomp
        seibun_key.delete_at(number%(seibun_key.length))
        nokori -= per
        break if nokori <= 0
        number = number < 100 ? number * number * 3759 : (number*2/3).to_i
      end
      @per_list = per_list.sort {|a, b| (-1) * (a <=> b)}

      # グラフ描画
      graph_list = []
      @per_list.each_with_index do |per, i|
        graph_list.push [@seibun_list[i], per]
      end
      @chart = LazyHighCharts::HighChart.new('pie') do |f|
        f.chart({defaultSeriesType: 'pie', margin: [50, 200, 60, 170]})
        f.series({
          type: 'pie',
          name: @name,
          data: graph_list
        })
      end
    end
  end

  # 勉強会資料
  def study
    render 'study', layout: 'impress'
  end

  # グループインタビュー資料
  def work
    render 'work', layout: 'impress'
  end

  protected
    def authenticate
      authenticate_or_request_with_http_basic('Administration') do |username, password|
        username == 'ike' && password == 'menmen'
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/views/commons/_google_analytics.html.haml
:coffee
  ((i, s, o, g, r, a, m) ->
    i['GoogleAnalyticsObject'] = r
    i[r] = i[r] or ->
      (i[r].q = i[r].q or []).push arguments
      return

    i[r].l = 1 * new Date
    a = s.createElement(o)
    m = s.getElementsByTagName(o)[0]
    a.async = 1
    a.src = g
    m.parentNode.insertBefore a, m
    return
  ) window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga'
  ga 'create', 'UA-64112790-1', 'auto'
  ga 'send', 'pageview'

app/views/commons/google_analytics.html.haml
:coffee
  ((i, s, o, g, r, a, m) ->
    i['GoogleAnalyticsObject'] = r
    i[r] = i[r] or ->
      (i[r].q = i[r].q or []).push arguments
      return

    i[r].l = 1 * new Date
    a = s.createElement(o)
    m = s.getElementsByTagName(o)[0]
    a.async = 1
    a.src = g
    m.parentNode.insertBefore a, m
    return
  ) window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga'
  ga 'create', 'UA-64112790-1', 'auto'
  ga 'send', 'pageview'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title カッパのポートフォリオ
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    - set_meta_tags description: 'カッパのポートフォリオ'
    - set_meta_tags keywords: 'カッパのポートフォリオ'
    - set_meta_tags open_graph: { title: 'カッパのポートフォリオ' }
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = yield :head
  %body
    .navbar.navbar-default
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => root_path} カッパのポートフォリオ
      .navbar-collapse.collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => root_path} 成果物一覧
          /%li
          /  %a{:href => "#"} Link
          /%li.dropdown
          /  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          /    Dropdown
          /    %b.caret
          /  %ul.dropdown-menu
          /    %li
          /      %a{:href => "#"} Action
          /    %li
          /      %a{:href => "#"} Another action
          /    %li
          /      %a{:href => "#"} Something else here
          /    %li.divider
          /    %li.dropdown-header Dropdown header
          /    %li
          /      %a{:href => "#"} Separated link
          /    %li
          /      %a{:href => "#"} One more separated link
        /%form.navbar-form.navbar-left
        /  %input.form-control.col-lg-8{:placeholder => "Search", :type => "text"}/
        /%ul.nav.navbar-nav.navbar-right
        /  %li
        /    %a{:href => "#"} Link
        /  %li.dropdown
        /    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        /      Dropdown
        /      %b.caret
        /    %ul.dropdown-menu
        /      %li
        /        %a{:href => "#"} Action
        /      %li
        /        %a{:href => "#"} Another action
        /      %li
        /        %a{:href => "#"} Something else here
        /      %li.divider
        /      %li
        /        %a{:href => "#"} Separated link
    .container
      = yield
    .footer_add
      = render "/commons/google_analytics"
      :javascript
        var nend_params = {"media":27178,"site":141059,"spot":376019,"type":1,"oriented":1};
      %script{ type: "text/javascript", src: "http://js1.nend.net/js/nendAdLoader.js" }

app/views/layouts/cosmo.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "rails_proving_ground"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "cosmo", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body

    = yield

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "cosmo"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/layouts/impress.html.haml
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=1024")
    %meta(name="apple-mobile-web-app-capable" content="yes")
    = stylesheet_link_tag "impress.css"


    = csrf_meta_tags
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
  %body.impress-not-supported
    = yield

app/views/layouts/yeti.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "rails_proving_ground"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "yeti", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body

    = yield

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "yeti"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/roots/bunseki.html.haml
= javascript_include_tag "bunseki"
%h1 社内の悪を暴くツール

%form{:method => "get", :action => "/bunseki"}
  %input.form-control#name{:type => "text", :placeholder => "名前を入力してください", :name => "name", :value => @name}


-if @name.present?
  .bs-docs-section
    .row
      .col-lg-4.col-lg-offset-1
        %table.table.table-striped.table-hover{:width => "50%"}
          - @per_list.each_with_index do |per, i|
            %tr
              %td #{@name}の#{per}%は「#{@seibun_list[i]}」です
      .col-lg-7
        = high_chart("#{@name}の脳内", @chart)

app/views/roots/index.html.haml
= content_for :head do
  = javascript_include_tag 'roots'

%h2 作ったもの一覧

%span.red ※ このページは Ruby on Rails で作られてます

%table.table.table-striped.table-hover
  %thead
    %tr
      %th.center 成果物
      %th.center 説明
  %tbody
    %tr
      %th.center= link_to "iOSアプリ　『戦場の勇者』", "https://itunes.apple.com/jp/app/zhan-changno-yong-zhe/id913443123?mt=8", target: "blank"
      %td
        ファミコン『戦場の狼』をオマージュした作品ですが、完成品は全くの別物。
        %br
        = link_to '開発言語', '#', class: 'btn btn-xs btn-primary open-ios'
    %tr
      %th.center= link_to "シューティングゲーム", "https://www.youtube.com/watch?v=m1FQUBi3At8", :target => "blank"
      %td
        youtubeにプレイ動画を公開中。
        %br
        = link_to '開発言語', '#', class: 'btn btn-xs btn-primary open-shoot'
    %tr
      %th.center= link_to "会社の悪を暴くツール", bunseki_path
      %td
        前職で遊びで作ったもの。グラフはhighcharts-railsで作成。
        %br
        = link_to '開発言語', '#', class: 'btn btn-xs btn-primary open-bunseki'
    %tr
      %th.center= link_to "LINE スタンプ　『リア充に憧れるカッパ』", "https://store.line.me/stickershop/product/1109084/ja", target: "blank"
      %td
        LINEスタンプ作って販売してみました。2/5申請して承認されたのは5/5。
    %tr
      %th.center= link_to "勉強会発表資料", work_path
      %td
        大企業とベンチャー企業のメリデメについて発表しました。
    %tr
      %th.center= link_to "githubアカウント", "https://github.com/InvokeTwoA", :target => "blank"
      %td
        各種ソースコードは公開中です。
    /%tr
    /  %td= link_to "勉強会資料", study_path
    /  %td
    /    今まで経験した３社それぞれでのPJの進め方。
    /%tr
    /  %td= link_to "技術ブログ", "http://invoketwoa.hatenablog.com/", :target => "blank"
    /  %td
    /    自分用のメモ。基本的にゴミ情報しかない。
    /    ※外部ページなので別ウィンドウ

app/views/roots/work.html.haml
= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true

.fallback-message
  %p
    ブラウザ対応してないっす (´；ω；｀)
  %p
    立ち去るが良い
#impress
  #title1.step.slide.active.present{data: {scale: 1, x:4000, y:0, "rotate-x" => -240, "rotate-y" => -90}}
    %h2 大手Web系IT企業の働き方
    .content
      %br
      %p{style: "text-align: center; padding: 10px"}
        = image_tag '/images/top_building.jpg'
        
  #step-1.step.slide.active.present{data: {x:-4000, y:-2000, "rotate-x" => 75, "rotate-y" => 75, scale: 1}}
    %h2 発表の流れ
    .content
      %ul
        %li 自己紹介+経歴
        %li 大企業の作業の進め方
        %li 大企業のメリット
        %li 大企業のデメリット
        %li ベンチャー企業の作業の進め方
        %li ベンチャー企業のメリット
        %li ベンチャー企業のデメリット
        %li まとめ

  / 全体のスライドが見える
  #overview.step{data: {x:"3000", y:"1500", scale:"14"}}

  / z: 8000 layer
  #step-o1.step.slide.active.present{data: {scale: 1, x:2000, y:2000, z:8000}}
    %h2 2006/9 - 2011/9　大企業入社
    .content
      %h3 志望動機
      %ul
        %li 色々できそう
        %li やっぱ大手は安心
        %li HP作成とか好きだったのでwebエンジニア志望

  #step-o2.step.slide.active.present{data: {scale: 1, x:4000, y:2000, z:8000, "rotate-y" => 90}}
    .content
      .top
        大手企業のメリット
      %br
      %br
      大手企業はどんなところ？

  #step-o2-1.step.slide.active.present{data: {scale: 1, x:6000, y:2000, z:8000, "rotate-y" => 90}}
    .content
      .top
        人が多い
      %br
      %div{style: 'text-align: center'}
        = image_tag '/images/people.jpg', width: 320, height: 250
      %br
      %ul
        %li 天才が多い(100人中1人の天才も、1万人取れば100人得られる)
        %li 社内技術が非常に充実
        %li 多くの人と出会える

  #step-o2-2.step.slide.active.present{data: {scale: 1, x:8000, y:2000, z:8000, "rotate-y" => 90}}
    .content
      .top
        大きく綺麗なオフィス
      %br
      %div{style: 'text-align: center'}
        = image_tag '/images/building.jpg', width: 100, height: 150
      %br
      %ul
        %li 充実した設備（最新のテスト端末、サーバー）

  #step-o2-3.step.slide.active.present{data: {scale: 1, x:10000, y:2000, z:8000, "rotate-y" => 90}}
    %h2 大企業のメリット
    .content
      %ul
        %li PVなど全ての数値が圧倒的
        %li 事業部が沢山。社内で転職みたいなこともできる
        %li マニュアル豊富(後述)
        %li 研修制度などしっかりしてる

  #step-o3.step.slide.active.present{data: {scale: 1, x:0, y:000, z:8000, "rotate-y" => 180}}
    .content
      .top 大企業の仕事の進め方
    %br
    %br
    %br
    大手とベンチャーでは仕事の進め方も全然違う

  #step-o4.step.slide.active.present{data: {scale: 1, x:0, y:2000, z:8000, "rotate-y" => 180}}
    %h2 仕事の進め方
    .content
      %ul
        %li 
          最優先すべきは
          %span.text-red
            品質
          。
          %br
          webページが数分表示できないだけで何百万の損失
        %li 分業制(企画、開発、制作、CS、運用)
        %li 
          完全な
          = link_to 'ウォーターフォール・モデル', 'http://ja.wikipedia.org/wiki/%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BF%E3%83%BC%E3%83%95%E3%82%A9%E3%83%BC%E3%83%AB%E3%83%BB%E3%83%A2%E3%83%87%E3%83%AB', target: "_blank"
      %p{style: "text-align: center;"}
        = image_tag '/images/shounin.jpg'

  #step-o5.step.slide.active.present{data: {scale: 1, x:-4000, y:4000, z:10000, "rotate-y" => 270}}
    %h3 新サービス企画書の例

    %div{style: 'border:#000000 solid 1px; padding: 15px'}
      %ul
        %li キャッチコピー
        %li ターゲットのユーザー層
        %li 自サービスの強み
        %li サービス内容
        %li 競合との差別化
        %li 作業コストの見積もり
    %br
    こういったテンプレートが洗練され尽くしてる。
    %br
    一個でも条件を満たさなければ行動はできない。
    %br
    %br
    便利と感じるか面倒と感じるかは人次第

  #step-o6.step.slide.active.present{data: {scale: 1, x:0000, y:4000, z:10000, "rotate-y" => 0}}
    .content
      .top
        大企業のデメリット

  #step-o7-1.step.slide.active.present{data: {scale: 1, x:2000, y:12000, z:10000, "rotate-y" => 90}}
    %h2 大企業のデメリット
    .content
      .top 人が多すぎること
      %br
      %br
      %ul
        %li 人が多い → 競争率が高い。埋没する人はする
        %li 怠ける人は怠ける
        %li 巨大すぎて組織の全体像の把握が難しい

  #step-o7-2.step.slide.active.present{data: {scale: 1, x:4000, y:12000, z:10000, "rotate-y" => 180}}
    %h2 大企業のデメリット
    .content
      %ul
        %li ルールが非常に多い（事故再発防止策）
        %li スピード感がない（品質 > スピード）
        %li チャレンジがしにくい（ローリスク推奨）
        %li 社内技術に慣れすぎると社外で通用しなくなる

  / 5000 layer
  #step-w0.step.slide.active.present{data: {scale: 1, x:2000, y:8000, z:5000}}
    .content
      .top
        ベンチャー企業の場合

  / 5000 layer
  #step-w1.step.slide.active.present{data: {scale: 1, x:2000, y:5000, z:5000}}
    %h2 ベンチャー企業での仕事の進め方
    .content
      %ul
        %li
          = link_to "アジャイル開発",  "http://ja.wikipedia.org/wiki/%E3%82%A2%E3%82%B8%E3%83%A3%E3%82%A4%E3%83%AB%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E9%96%8B%E7%99%BA", target: "_blank"
          = link_to "https://www.google.co.jp/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%E3%82%A2%E3%82%B8%E3%83%A3%E3%82%A4%E3%83%AB%20%E6%84%8F%E5%91%B3", target: "_blank" do
            = image_tag "/images/cat.png"
        %li 最小人数のチーム構成
        %li 現場判断が多い
                                                    
  / 0 layer
  #step-w2.step.slide.active.present{data: {scale: 1, x:4000, y:5000}}
    .top
      ベンチャー企業のメリット

  / 0 layer
  #step-w3.step.slide.active.present{data: {scale: 1, x:4000, y:7000}}
    %h2 ベンチャー企業のメリット
    .content
      %ul
        %li 個人の裁量が大きい
        %li スピード感がある(ルール等が少ない)
        %li チャレンジがしやすい。評価される
        %li お金の動きや数値のリアルさを知れる
        %li 会社の成長性(変化)に期待できる。一攫千金
        %li 偉い人とも直接議論できる

  #step-w4.step.slide.active.present{data: {scale: 1, x:4000, y:9000}}
    .top
      ベンチャー企業のメリット

  #step-w5.step.slide.active.present{data: {scale: 1, x:6000, y:12000}}
    %h2 デメリット
    .content
      %ul
        %li
          倒産のリスク。
          %span.text-red 赤字
          により会社の雰囲気が変わる
        %li マニュアルなどない
        %li ルールや研修なども少ない
        %li 人が少ない
      %p{style: "text-align: right;"}
        = image_tag "/images/ghost.png", width: 64, height: 64
 
  #step-matome1.step.slide.active.present{data: {scale: 1, x:0, y:5000, z:3000, "rotate-y" => 90}}
    %h2 それぞれの特徴まとめ
    .content
      %table.table.table-striped.table-hover
        %tr
          %th 
          %th 大企業
          %th ベンチャー企業
        %tr
          %td 品質
          %td 高い
          %td 優先度は低め
        %tr
          %td スピード感
          %td 遅い
          %td 速い
        %tr
          %td 会社の安定性
          %td 潰れはしない
          %td 変化は激しい

  #step-dev6-3.step.slide.active.present{data: {scale: 1, x:2000, y:-6000, z:-3000, "rotate-x" => "180", "rotate-y" => "270"}}
    %h2 結論
    .content
      %ul
        %li 大手とベンチャー、どちらが良いという事はない
        %li 自分にあった企業形態を選んでください
      %table.table.table-striped.table-hover
        %tr
          %th.center 品質を取るか、スピードを取るか
        %tr
          %th.center ルールを選ぶか、自由を選ぶか
        %tr
          %th.center 安定を望むか、変化を望むか
      
  #step-dev6-4.step.slide.active.present{data: {scale: 5, x:0, y:-2000, z:4000, "rotate-z" => "90", "rotate-x" => '70'}}
    %h2 おしまい

= javascript_include_tag "impress.js"
:javascript
  impress().init();